import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ContextProvider from "@/components/Providers/ContextProvider";
import AuthProvider from "@/components/Providers/AuthProvider";
import CheckProvider from "@/components/Providers/CheckProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Perfume",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CheckProvider>
            <ContextProvider>
              <Navbar />
              {children}
            </ContextProvider>
          </CheckProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
