import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ContextProvider from "@/ContextProvider/ContextProvider";
import AuthProvider from "@/components/Providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Perfume",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ContextProvider>
            <Navbar />
            {children}
          </ContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
